### ISSUE TITLE
Downloads being shown inside popup instead of sidebar

### ISSUE THREAD

**Issue by kasutajaimin** [FranklinDM/TGS#15]
After opening something from OpenDownload dialog downloads view will open as a popup bubble from sidebar button instead of inside the sidebar.
Same as vanilla AiOS: https://forum.palemoon.org/viewtopic.php?t=13795
![clipboard01](https://user-images.githubusercontent.com/31406326/29771157-081f69f4-8bfb-11e7-86f5-925ee80008fa.png)

**Comment by fofajardo** [comment]
Thank you for reporting this bug! This will be fixed in the next release. This isn't really connected to OpenDownload, but instead, an effect of the new way downloads are implemented in PM27+.

A new commit will be up soon on the development branch to fix this.

**Technical Details:**
Added a mutation observer to check if downloads indicator is an element existing and change it's oncommand attribute accordingly.
