### ISSUE TITLE
Icon corruption under PMOpera theme

### ISSUE THREAD

**Issue by kasutajaimin** [FranklinDM/TGS#16]
AiOS vs TGS:
![capture1](https://user-images.githubusercontent.com/31406326/29771362-0448d4d6-8bfc-11e7-9058-07e9db9bbd2a.PNG)![capture2](https://user-images.githubusercontent.com/31406326/29771361-044740da-8bfc-11e7-82ba-3e01f3435348.PNG)

**Comment by fofajardo** [comment]
Thank you for reporting this bug! This will be fixed in the next release.

A new commit will be up soon on the development branch to fix this.

**Technical Details**:
Some of the selectors specify (aios-appOS) which is an attribute that is set to the main window to be able to identify what OS is being used, however during the time when AiOS was being refactored (the version you're using isn't affected because that is an older version if I'm not mistaken), the method called to set this attribute (and some others) was removed (see: 322a1b04dcbef411578c47814e081a03a55e6747).

This broke those selectors and this one you're seeing right now is its effect. **aios_buttons_generic.css**' selectors are being applied even though it isn't supposed to.
